<script setup>
import { onMounted, ref } from 'vue';
const apiBase = ref(localStorage.getItem('iptv_api_base') || '');
const adminToken = ref(localStorage.getItem('iptv_admin_token') || '');
const dashboard = ref(null), sources = ref([]), channels = ref([]), programs = ref([]), users = ref([]), plans = ref([]), keys = ref([]);
const sourceName = ref(''), sourceUrl = ref(''), epgUrl = ref(''), newUsername = ref(''), newDays = ref(30), userSearch = ref(''), channelSearch = ref('');
const newPlan = ref({ name: '', channels_limit: 0, daily_limit: 0, epg_enable: true }), keyName = ref('');
const channelPage = ref(1), channelTotal = ref(0), userPage = ref(1), userTotal = ref(0), epgChannel = ref(''), loading = ref(false), message = ref('');
async function request(path, options = {}) { const headers = new Headers(options.headers || {}); headers.set('X-Admin-Token', adminToken.value); const r = await fetch(`${apiBase.value}${path}`, { ...options, headers }); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || `HTTP ${r.status}`); return d; }
const jsonOptions = body => ({ method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body) });
async function loadSources(){ sources.value=(await request('/admin/source/list?size=100')).sources||[]; }
async function loadChannels(){ const p=new URLSearchParams({page:String(channelPage.value),size:'20'}); if(channelSearch.value.trim())p.set('search',channelSearch.value.trim()); const d=await request(`/admin/channel/list?${p}`); channels.value=d.channels||[]; channelTotal.value=d.total||0; }
async function loadEpg(){ const p=new URLSearchParams({limit:'100'}); if(epgChannel.value)p.set('channel_id',epgChannel.value); programs.value=(await request(`/admin/epg/list?${p}`)).programs||[]; }
async function loadUsers(){ const p=new URLSearchParams({page:String(userPage.value),size:'20'}); if(userSearch.value.trim())p.set('search',userSearch.value.trim()); const d=await request(`/admin/user/list?${p}`); users.value=d.users||[]; userTotal.value=d.total||0; }
async function loadPlans(){ plans.value=(await request('/admin/plan/list')).plans||[]; }
async function loadKeys(){ keys.value=(await request('/admin/api-key/list')).keys||[]; }
async function load(){ loading.value=true; message.value=''; try{ dashboard.value=await request('/admin/dashboard'); await Promise.all([loadSources(),loadChannels(),loadEpg(),loadUsers(),loadPlans(),loadKeys()]); }catch(e){message.value=e.message}finally{loading.value=false} }
async function addSource(){if(!sourceName.value||!sourceUrl.value)return;try{await request('/admin/source/add',jsonOptions({name:sourceName.value,url:sourceUrl.value}));sourceName.value='';sourceUrl.value='';await loadSources()}catch(e){message.value=e.message}}
async function removeSource(id){try{await request('/admin/source/delete',jsonOptions({id}));await loadSources()}catch(e){message.value=e.message}}
async function removeChannel(id){try{await request('/admin/channel/delete',jsonOptions({id}));await loadChannels()}catch(e){message.value=e.message}}
async function toggleChannel(c){try{await request('/admin/channel/update',jsonOptions({id:c.id,status:c.status==='disabled'?'active':'disabled'}));await loadChannels()}catch(e){message.value=e.message}}
async function importEpg(){if(!epgUrl.value.trim())return;try{const r=await request('/admin/epg/import',jsonOptions({url:epgUrl.value.trim()}));message.value=`EPG导入完成：${r.importedPrograms||0} 个节目，匹配 ${r.matchedChannels||0} 个频道`;epgUrl.value='';await loadEpg()}catch(e){message.value=e.message}}
async function clearOldEpg(){try{await request('/admin/epg/clear',jsonOptions({before:Date.now()}));await loadEpg()}catch(e){message.value=e.message}}
async function addUser(){if(!newUsername.value.trim())return;try{const expire=Date.now()+Number(newDays.value||30)*86400000;const r=await request('/admin/user/add',jsonOptions({username:newUsername.value.trim(),expire}));message.value=`用户已创建：${r.username}，Token：${r.token}`;newUsername.value='';await loadUsers()}catch(e){message.value=e.message}}
async function toggleUser(u){try{await request('/admin/user/update',jsonOptions({id:u.id,status:u.status==='disabled'?'active':'disabled'}));await loadUsers()}catch(e){message.value=e.message}}
async function resetToken(u){try{const r=await request('/admin/user/reset-token',jsonOptions({id:u.id}));message.value=`${u.username} 新 Token：${r.token}`;await loadUsers()}catch(e){message.value=e.message}}
async function removeUser(id){try{await request('/admin/user/delete',jsonOptions({id}));await loadUsers()}catch(e){message.value=e.message}}
async function savePlan(){if(!newPlan.value.name.trim())return;try{await request('/admin/plan/save',jsonOptions(newPlan.value));newPlan.value={name:'',channels_limit:0,daily_limit:0,epg_enable:true};await loadPlans()}catch(e){message.value=e.message}}
async function removePlan(id){try{await request('/admin/plan/delete',jsonOptions({id}));await loadPlans()}catch(e){message.value=e.message}}
async function createKey(){if(!keyName.value.trim())return;try{const r=await request('/admin/api-key/create',jsonOptions({name:keyName.value.trim()}));message.value=`API Key：${r.key}`;keyName.value='';await loadKeys()}catch(e){message.value=e.message}}
async function toggleKey(k){try{await request('/admin/api-key/toggle',jsonOptions({id:k.id}));await loadKeys()}catch(e){message.value=e.message}}
async function removeKey(id){try{await request('/admin/api-key/delete',jsonOptions({id}));await loadKeys()}catch(e){message.value=e.message}}
function saveApi(){localStorage.setItem('iptv_api_base',apiBase.value.replace(/\/$/,''));localStorage.setItem('iptv_admin_token',adminToken.value);load()}
function searchChannels(){channelPage.value=1;loadChannels().catch(e=>message.value=e.message)}
function searchUsers(){userPage.value=1;loadUsers().catch(e=>message.value=e.message)}
onMounted(()=>{if(apiBase.value&&adminToken.value)load()})
</script>
<template><main class="shell"><header class="header"><div><p class="eyebrow">IPTV-ALPHA</p><h1>管理后台</h1></div><span class="badge">v3.0-beta.7</span></header>
<section class="config card"><label>Worker API 地址</label><div class="row"><input v-model="apiBase" placeholder="https://your-worker.example.workers.dev"/></div><label class="token-label">Admin Token</label><div class="row"><input v-model="adminToken" type="password" placeholder="Cloudflare Worker ADMIN_TOKEN"/><button @click="saveApi">保存并连接</button></div></section>
<p v-if="message" class="notice">{{message}}</p>
<section class="stats"><div class="card stat"><span>直播源</span><strong>{{dashboard?.sources??'-'}}</strong></div><div class="card stat"><span>频道</span><strong>{{dashboard?.channels??'-'}}</strong></div><div class="card stat"><span>用户</span><strong>{{dashboard?.users??'-'}}</strong></div><div class="card stat"><span>节目</span><strong>{{dashboard?.programs??'-'}}</strong></div></section>
<section class="card"><div class="section-title"><h2>用户订阅</h2><span>{{userTotal}} 个用户</span></div><div class="form row"><input v-model="newUsername" placeholder="用户名"/><input v-model.number="newDays" type="number" min="1" placeholder="有效天数"/><button @click="addUser">创建用户</button></div><div class="row"><input v-model="userSearch" @keyup.enter="searchUsers" placeholder="搜索用户名"/><button @click="searchUsers">搜索</button></div><div v-for="u in users" :key="u.id" class="source"><div><strong>{{u.username}}</strong><small>{{u.status}} · 到期：{{new Date(u.expire).toLocaleString()}} · Token：{{u.token}}</small></div><div class="actions"><button class="ghost" @click="toggleUser(u)">{{u.status==='disabled'?'启用':'禁用'}}</button><button class="ghost" @click="resetToken(u)">重置Token</button><button class="danger" @click="removeUser(u.id)">删除</button></div></div><div class="pagination"><button :disabled="userPage<=1" @click="userPage--;loadUsers()">上一页</button><span>第 {{userPage}} 页</span><button :disabled="userPage*20>=userTotal" @click="userPage++;loadUsers()">下一页</button></div></section>
<section class="card"><div class="section-title"><h2>套餐管理</h2><span>{{plans.length}} 个套餐</span></div><div class="form row"><input v-model="newPlan.name" placeholder="套餐名称"/><input v-model.number="newPlan.channels_limit" type="number" min="0" placeholder="频道上限，0不限"/><input v-model.number="newPlan.daily_limit" type="number" min="0" placeholder="每日请求，0不限"/><label class="check"><input v-model="newPlan.epg_enable" type="checkbox"/> EPG</label><button @click="savePlan">保存套餐</button></div><div v-for="p in plans" :key="p.id" class="source"><div><strong>{{p.name}}</strong><small>频道：{{p.channels_limit||'不限'}} · 每日：{{p.daily_limit||'不限'}} · EPG：{{p.epg_enable?'开启':'关闭'}}</small></div><button class="danger" @click="removePlan(p.id)">删除</button></div></section>
<section class="card"><div class="section-title"><h2>API Key</h2><span>{{keys.length}} 个 Key</span></div><div class="form row"><input v-model="keyName" placeholder="Key 名称，例如：播放器API"/><button @click="createKey">创建 Key</button></div><div v-for="k in keys" :key="k.id" class="source"><div><strong>{{k.name}}</strong><small>{{k.key}} · {{k.status}}</small></div><div class="actions"><button class="ghost" @click="toggleKey(k)">{{k.status==='active'?'禁用':'启用'}}</button><button class="danger" @click="removeKey(k.id)">删除</button></div></div></section>
<section class="card"><div class="section-title"><h2>直播源管理</h2><button class="ghost" @click="loadSources">刷新</button></div><div class="form row"><input v-model="sourceName" placeholder="源名称"/><input v-model="sourceUrl" placeholder="M3U / TXT / M3U8 URL"/><button @click="addSource">添加</button></div><div v-for="s in sources" :key="s.id" class="source"><div><strong>{{s.name}}</strong><small>{{s.url}}</small></div><button class="danger" @click="removeSource(s.id)">删除</button></div></section>
<section class="card"><div class="section-title"><h2>频道管理</h2><span>{{channelTotal}} 个频道</span></div><div class="row"><input v-model="channelSearch" @keyup.enter="searchChannels" placeholder="搜索频道名称 / URL"/><button @click="searchChannels">搜索</button></div><div v-for="c in channels" :key="c.id" class="channel"><div class="channel-main"><img v-if="c.logo" :src="c.logo" alt=""/><div><strong>{{c.name}}</strong><small>{{c.group_name||'未分组'}} · {{c.url}}</small></div></div><div class="actions"><button class="ghost" @click="toggleChannel(c)">{{c.status==='disabled'?'启用':'禁用'}}</button><button class="danger" @click="removeChannel(c.id)">删除</button></div></div><div class="pagination"><button :disabled="channelPage<=1" @click="channelPage--;loadChannels()">上一页</button><span>第 {{channelPage}} 页</span><button :disabled="channelPage*20>=channelTotal" @click="channelPage++;loadChannels()">下一页</button></div></section>
<section class="card"><div class="section-title"><h2>EPG节目单</h2><button class="ghost" @click="loadEpg">刷新</button></div><div class="row"><input v-model="epgUrl" placeholder="XMLTV / EPG 地址"/><button @click="importEpg">导入 EPG</button><button class="danger" @click="clearOldEpg">清理过期</button></div><div v-for="p in programs" :key="p.id" class="source"><div><strong>{{p.title}}</strong><small>{{new Date(p.start_time).toLocaleString()}} → {{new Date(p.end_time).toLocaleString()}} · Channel {{p.channel_id}}</small></div></div></section>
</main></template>
